### ISSUE TITLE
3D CAD / STEP

### ISSUE THREAD

**Issue by yashmulgaonkar** [adafruit/3.5inch-TFT-Breakout-PCB#1]
Hello Adafruit, 
Would it be possible to get a STEP file of this screen?
Thanks!

**Comment by dherrada** [comment]
@yashm I can make one for you. If I don't get to it in a few days please send me a message to remind me as I am very prone to forgetting about these things

**Comment by danieldelvecchio** [comment]
I am actually here for the same thing as Yashm.  I need the STEP file to place this screen into a product design.  Any movement on getting on output?

**Comment by ladyada** [comment]
hi we dont have any ETA to make it, you could use
https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3651%203.5in%20TFT%20FeatherWing
or open an issue on that repo

**Comment by danieldelvecchio** [comment]
This answers my question. Thank you!


Daniel DelVecchio
M: +1 (480) 316-4132
***@***.******@***.***>

From: ladyada ***@***.***>
Sent: Thursday, July 8, 2021 8:27 AM
To: adafruit/3.5inch-TFT-Breakout-PCB ***@***.***>
Cc: DelVecchio, Daniel E. ***@***.***>; Comment ***@***.***>
Subject: [CAUTION: EXTERNAL]Re: [adafruit/3.5inch-TFT-Breakout-PCB] 3D CAD / STEP (#1)

WARNING: This email originated from outside of West Pharmaceutical Services, Inc. Inspect the sender's display name and email address closely. Do not click links or open attachments unless you recognize the sender and are expecting the message. Never provide your Login ID and password to anyone.


hi we dont have any ETA to make it, you could use
https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/3651%203.5in%20TFT%20FeatherWing<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadafruit%2FAdafruit_CAD_Parts%2Ftree%2Fmain%2F3651%25203.5in%2520TFT%2520FeatherWing&data=04%7C01%7C%7C9eeea7c1f1b04dffd2d808d94224c602%7C61a70d37ff6345e3bb68f0edbf718ffd%7C0%7C1%7C637613547984656775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IAM7NyoeClh12CLFBYPsgUgALXEwytM5P309%2FkPxhtE%3D&reserved=0>
or open an issue on that repo

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadafruit%2F3.5inch-TFT-Breakout-PCB%2Fissues%2F1%23issuecomment-876533237&data=04%7C01%7C%7C9eeea7c1f1b04dffd2d808d94224c602%7C61a70d37ff6345e3bb68f0edbf718ffd%7C0%7C1%7C637613547984656775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FcX3AB20smXS568NkYmKFsb3EMEvUH7evLLb2LH90FU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUYZ7WGJX2QB2TAVIB5NT3LTWW7SVANCNFSM47WDG3FA&data=04%7C01%7C%7C9eeea7c1f1b04dffd2d808d94224c602%7C61a70d37ff6345e3bb68f0edbf718ffd%7C0%7C1%7C637613547984666766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CaEpIIF%2FEH544CTF2SwsieJw2Dhl3Jw7ZtUPFJZdzEc%3D&reserved=0>.

Find West on Twitter <http://twitter.com/#!/WestPharma> and LinkedIn<http://www.linkedin.com/company/west-pharmaceutical-services?trk=fc_badge>.

________________________________
The contents of this message are confidential and may be privileged. If you have received this message in error, please permanently delete it, along with any files that may be attached to this message, without reading, printing, copying, forwarding or otherwise distributing it. Please notify the sender of the error immediately so that we can prevent it from happening again.
